//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyScreenshot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dictionary_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyScreenshot.Resources.Dictionary_ru", typeof(Dictionary_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все настройки сохранены.
        /// </summary>
        internal static string AllSettingsSaved {
            get {
                return ResourceManager.GetString("AllSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кликните по значку фотоаппарата, чтобы посмотреть доступные комманды.
        /// </summary>
        internal static string ClickToCameraIcon {
            get {
                return ResourceManager.GetString("ClickToCameraIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать и сохранить:.
        /// </summary>
        internal static string CreateAndSave {
            get {
                return ResourceManager.GetString("CreateAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать и загрузить:.
        /// </summary>
        internal static string CreateAndUpload {
            get {
                return ResourceManager.GetString("CreateAndUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать и использовать ножницы:.
        /// </summary>
        internal static string CreateAndUseSnippingTool {
            get {
                return ResourceManager.GetString("CreateAndUseSnippingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип файла:.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна или несколько выбранных клавиш не поддерживаются.
        /// </summary>
        internal static string HotkeyNotSupported {
            get {
                return ResourceManager.GetString("HotkeyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горячие клавиши:.
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на скриншот была скопирована в буфер обмена.
        /// </summary>
        internal static string ImageUrlWasCopied {
            get {
                return ResourceManager.GetString("ImageUrlWasCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скриншот был сохранен в папку.
        /// </summary>
        internal static string ImageWasSaved {
            get {
                return ResourceManager.GetString("ImageWasSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь для скриншотов:.
        /// </summary>
        internal static string PathForScreenshots {
            get {
                return ResourceManager.GetString("PathForScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите комбинацию клавиш CTRL+V, чтобы вставить ссылку на скриншот.
        /// </summary>
        internal static string PressToInsertImageLink {
            get {
                return ResourceManager.GetString("PressToInsertImageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готов делать скриншот.
        /// </summary>
        internal static string ReadyToMakeScreenshot {
            get {
                return ResourceManager.GetString("ReadyToMakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скриншот.
        /// </summary>
        internal static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Украинский.
        /// </summary>
        internal static string Ukrainian {
            get {
                return ResourceManager.GetString("Ukrainian", resourceCulture);
            }
        }
    }
}
